# Etapa 1: Build con Node
FROM node:18-alpine AS build

WORKDIR /app

# Copiamos package.json y package-lock.json primero
COPY package*.json ./

# Variables que se pasan desde docker-compose (deben estar ANTES del npm install)
ARG VITE_API_URL=http://localhost:8080
ENV VITE_API_URL=$VITE_API_URL

# Instalar dependencias (incluyendo devDependencies para el build)
RUN npm ci

# Copiamos el resto del código
COPY . .

# Construimos la app (genera /dist)
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine

# Borrar html default
RUN rm -rf /usr/share/nginx/html/*

# Copiar build generado por Node
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración de Nginx
COPY ./nginx.config /etc/nginx/conf.d/default.conf

# Exponer puerto 80
EXPOSE 80

# Iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
